# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
                ('data', models.DateField()),
                ('godzina', models.SmallIntegerField(max_length=2)),
                ('miejsce', models.CharField(max_length=250)),
                ('uwagi', models.CharField(max_length=500)),
            ],
        ),
    ]
