# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='godzina',
            field=models.CharField(max_length=10),
        ),
    ]
